export const HttpResponse = {
  UNHANDLED_ERROR:"Unhandled error",
  SERVER_ERROR: 'Internal server error',
  USER_EXIST: 'User already exist',
  PAGE_NOT_FOUND: 'Route not found',
  USER_NOT_FOUND: 'User not found',
  PASSWORD_INCORRECT: 'Incorrect password, try again',
  NO_TOKEN: 'Token not provided',
  OTP_INCORRECT: 'Incorrect otp, try again',
  OTP_NOT_FOUND: 'Otp not found',
  INVALID_CREDENTIALS: 'Invalid credentials',
  USER_CREATION_FAILED: 'User creation failed',
  USER_CREATION_SUCCESS: 'User created successfully',
  EMAIL_EXIST: 'Email already exist',
  INVALID_EMAIL: 'Invalid email address',
  UNEXPECTED_KEY_FOUND: 'Unexpected key found',
  NOT_ENOUGH_QUANTITY:"Not enough quantity",

  TOKEN_EXPIRED: 'Token not valid or expired!',
  PASSWORD_CHANGE_SUCCESS: 'Password changed successfully!',
  UNAUTHORIZED: 'Unauthorized access!',
  USER_FIELD_EXIST: 'Username Or mobile Already Exist',
  NO_PAYLOAD: 'Payload not found',

  SAME_USERNAME: 'Cannot change to old username',
  RESOURCE_FOUND: 'Resource found.',
  RESOURCE_UPDATED: 'Resource updated.',

  INVENTORY_EXIST : "Inventory already exist",
  PRODUCT_ADD:"Product added",
  PRODUCT_EDIT:"Product edit success",
  DELETE_SUCCESS:"Delete success",
  FAILED:"Failed",
  SUCCESS:"Success"
};
